team-alcoholic/jumo-client

README.md
=> Byob 66 지라 깃허브 연동 설정

package-lock.json, package.json, src/app/globals.css, src/app/join/page.tsx, src/app/layout.tsx, src/component/selectRegion.tsx, src/style/join.module.css, src/style/selectRegion.module.css
**Jira 티켓: [BYOB-51]**
<br>
**지역 선택 컴포넌트 구현**
- 시/도 - 시/군/구 - 읍/면/동 3가지 범주로 선택
**회원가입 양식 페이지 일부 구현**
- 선택한 지역 콘솔에 띄우는 부분까지 구현
**해야 할 일**
- 회원가입 페이지 전체 완성하기
[BYOB-51]: https://swm-alcoholic.atlassian.net/browse/BYOB-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-51] 지역 선택 컴포넌트 구현

src/component/selectRegion.tsx
**Jira 티켓: [BYOB-75]**
<br>
**오류 수정**
하위 분류를 선택한 상태에서 상위 분류를 바꾸게 되면 하위 분류 선택값이 초기화되지 않고 남아있는 문제 발견
코드를 보니 상위 분류 선택값을 없앤 경우에만 하위 선택값도 초기화되도록 구현해두었음
[BYOB-75]: https://swm-alcoholic.atlassian.net/browse/BYOB-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-75] 지역 선택 컴포넌트에서 상위 분류 변경 시 하위 분류 초기화되지 않는 문제 해결

.dockerignore
**Jira 티켓: [BYOB-93]**
<br>
- 도커 파일 복사시 .env도 같이 옮기도록 변경
[BYOB-93]: https://swm-alcoholic.atlassian.net/browse/BYOB-93?atlOrigin=eyJpIjoiZDE4MjBiYjE1OWQ2NDlkMThkNDBmYjlmNDU1MTZkZmYiLCJwIjoiaiJ9
=> [BYOB-93] 프론트 환경 변수 문제 해결

Dockerfile
**Jira 티켓: [BYOB-94]**
<br>
- 모임 상세 페이지 사진 안 보이는 문제 해결
- 도커 빌드 파일 복사시 next.config.mjs도 같이 옮기도록 변경
- <img width="634" alt="스크린샷 2024-07-19 오전 1 49 56" src="https://github.com/user-attachments/assets/4950bb66-937d-4fd6-9be0-75891342c635">
[BYOB-94]: https://swm-alcoholic.atlassian.net/browse/BYOB-94?atlOrigin=eyJpIjoiZDE4MjBiYjE1OWQ2NDlkMThkNDBmYjlmNDU1MTZkZmYiLCJwIjoiaiJ9
=> [BYOB-94] 모임 상세 페이지 이미지 안 나오는 문제 해결

src/app/meetings/[mId]/page.tsx, src/app/meetings/page.tsx
**Jira 티켓: [BYOB-101]**
<br>
모임 관련 API 요청 경로 수정
[BYOB-101]: https://swm-alcoholic.atlassian.net/browse/BYOB-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-101] 서버 API 수정에 따른 모임 관련 API 요청 경로 수정

.github/workflows/front_dev.yml, package-lock.json, package.json, src/app/layout.tsx
**Jira 티켓: [BYOB-105]**
<br>
Google Analytics 연결 테스트를 위한 라이브러리 설치 및 환경변수 세팅
[BYOB-105]: https://swm-alcoholic.atlassian.net/browse/BYOB-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-105] Google Analytics 연결 테스트

.github/workflows/front_dev.yml, Dockerfile
**Jira 티켓: [BYOB-117]**
<br>
- 도커 허브 ecr로 교체
- alpine -> slim
[BYOB-117]: https://swm-alcoholic.atlassian.net/browse/BYOB-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-117] 도커 허브 ecr로 교체

new-types.d.ts, src/app/meetings/[mId]/page.tsx, src/app/meetings/page.tsx, src/components/MeetingCard/MeetingCard.tsx, src/components/MeetingCard/MeetingCardSkeleton.tsx, src/utils/format.ts, tsconfig.json
**Jira 티켓: [BYOB-108]**
<br>
**1. type 리팩토링**
공식문서에 언급된 대로, 커스텀 타입들을 new-types.d.ts에 모아서 관리할 수 있도록 리팩토링
https://nextjs.org/docs/pages/building-your-application/configuring/typescript#custom-type-declarations
**2. 모임 목록 페이지 type 관련 리팩토링**
기존 모임일시가 null값인 경우를 처리하는 로직이 없어 에러 발생하는 부분을 수정
[BYOB-108]: https://swm-alcoholic.atlassian.net/browse/BYOB-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-108] 모임 목록 페이지에서 type 관련 리팩토링 및 예외처리

src/app/meetings/[mId]/page.tsx, src/components/MeetingCard/MeetingCard.tsx, src/constants/communityNames.ts, src/utils/format.ts
**Jira 티켓: [BYOB-132]**
<br>
- 본문 줄 바꿈 안되는 문제 해결
- 시간 문제 해결
- 외부 커뮤니티 표시 기능 추가
[BYOB-132]: https://swm-alcoholic.atlassian.net/browse/BYOB-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-132] 미팅 상세 화면 크롤링 데이터 조회 시 깨짐 해결

new-types.d.ts, src/app/meetings/[mId]/page.tsx, src/app/meetings/page.tsx, src/components/MeetingCard/MeetingCard.tsx, src/components/MeetingCard/MeetingCardSkeleton.tsx, src/components/MeetingCard/StyledComponent.tsx, src/constants/communityNames.ts, src/utils/format.ts, src/utils/urlConverter.ts
**Jira 티켓: [BYOB-140]**
<br>
- 정렬 옵션 바꾸는 필터
- 이미지 cors 문제 해결
- 글 작성일 보여주는 기능
- 네이버 카페 모바일 버전 이동 링크 추가
[BYOB-140]: https://swm-alcoholic.atlassian.net/browse/BYOB-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-140] 모임 목록 정렬 기능 및 자투리 기능

src/app/meetings/page.tsx, src/app/provider.tsx
**Jira 티켓: [BYOB-143]**
<br>
**React Query 관련 캐싱 설정**
- staleTime 5분으로 설정
- refetchOnWindowFocus를 false로 설정
**모임목록페이지의 useInfiniteQuery 수정**
- sortOption 변경 시 refetch하지 않도록 기존 코드를 수정
[BYOB-143]: https://swm-alcoholic.atlassian.net/browse/BYOB-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-143] React Query 관련 설정 추가 및 기존 코드 수정

src/app/meetings/page.tsx, src/components/UserFeedbackCard/UserFeedbackCard.tsx
**Jira 티켓: [BYOB-158]**
<br>
- 유저 피드백 컴포넌트 버튼 텍스트 수정
- 모임 목록 페이지 주류 필터 버튼 디자인 수정
[BYOB-158]: https://swm-alcoholic.atlassian.net/browse/BYOB-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-158] 모임목록페이지 자잘한 디자인 수정

src/api/tastingNotesApi.ts, src/app/login/page.tsx, src/app/tasting-notes/[id]/page.tsx, src/app/tasting-notes/new/page.tsx
**Jira 티켓: [BYOB-168]**
<br>
- 테이스팅 노트 api 연동 및 로그인 처리
[BYOB-168]: https://swm-alcoholic.atlassian.net/browse/BYOB-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-168] 테이스팅 노트 api 연동 및 로그인 처리

src/app/liquors/[id]/page.tsx, src/app/tasting-notes/new/page.tsx
**Jira 티켓: [BYOB-177]**
<br>
**작업 사항**
주류 상세정보 페이지 하단의 테이스팅 리뷰 컴포넌트에, 테이스팅 리뷰 작성 버튼을 추가함
버튼 클릭 시 해당 주류에 대한 테이스팅노트를 작성하는 페이지로 이동
[BYOB-177]: https://swm-alcoholic.atlassian.net/browse/BYOB-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-178] 주류 상세정보 페이지 및 테이스팅노트 작성 페이지 연결

new-types.d.ts, next.config.mjs, package-lock.json, package.json, src/app/liquors/[id]/page.tsx, src/app/liquors/page.tsx, src/app/tasting-notes/[id]/page.tsx, src/components/FloatingButton/FloatingButton.tsx, src/components/LiquorUserTastingComponent/LiquorUserTastingComponent.tsx, src/components/SingleTastingComponent/SingleTastingComponent.tsx, src/styles/globals.css
**Jira 티켓: [BYOB-182]**
<br>
**작업 사항**
- 테이스팅 리뷰 작성 버튼을 플로팅 버튼으로 변경
- 테이스팅 리뷰 목록 카드 내용 및 폰트 수정
- 테이스팅 리뷰 목록 카드에 점수 보이기
[BYOB-182]: https://swm-alcoholic.atlassian.net/browse/BYOB-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-182] 주류 상세정보 페이지 디자인 수정

src/app/liquors/page.tsx, src/app/meetings/page.tsx, src/app/mypage/page.tsx, src/app/tasting-notes/[id]/edit/page.tsx, src/app/temp/page.tsx, src/components/LayoutComponents/HeaderComponent.tsx, src/components/LayoutComponents/NavigationComponent.tsx, src/components/LiquorUserTastingComponent/LiquorUserTastingComponent.tsx, src/components/LiquorUserTastingComponent/UserTastingComponent.tsx, src/components/TastingNotesComponent/TabContentComponent.tsx
**Jira 티켓: [BYOB-194]**
<br>
**작업 사항**
- 테이스팅 노트 입력 수정시 네비바 비활성화
- 로그인시 자동으로 로그인 리다이랙션
- 수정시 연관 노트 불러오기
[BYOB-194]: https://swm-alcoholic.atlassian.net/browse/BYOB-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-194] 테이스팅 노트 입력 수정시 네비바 비활성화

new-types.d.ts, package-lock.json, package.json, src/app/liquors/[id]/page.tsx, src/app/liquors/new/page.tsx, src/app/liquors/page.tsx, src/app/mypage/page.tsx
**Jira 티켓: [BYOB-196]**
<br>
- 주류 추가 기능 구현
- 주류 검색시 로딩바 구현
[BYOB-196]: https://swm-alcoholic.atlassian.net/browse/BYOB-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-196] 주류 추가 페이지

.github/workflows/frontend_dev.yml, .github/workflows/frontend_prod.yml, .gitignore, next.config.mjs, package-lock.json, package.json
**Jira 티켓: [BYOB-198]**
<br>
- 센트리 적용
[BYOB-198]: https://swm-alcoholic.atlassian.net/browse/BYOB-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-198] 센트리 적용

.github/workflows/frontend_dev.yml, .github/workflows/frontend_prod.yml, Dockerfile, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/app/global-error.tsx, src/instrumentation.ts
**Jira 티켓: [BYOB-199]**
<br>
- 센트리 오류 해결
[BYOB-199]: https://swm-alcoholic.atlassian.net/browse/BYOB-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-199] 센트리 오류 픽스

src/app/tasting-notes/[id]/edit/page.tsx, src/app/tasting-notes/new/page.tsx
**Jira 티켓: [BYOB-203]**
<br>
- 수정 버튼 구현
[BYOB-203]: https://swm-alcoholic.atlassian.net/browse/BYOB-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-203] 테이스팅 노트 작성 수정시 취소 버튼 구현

src/app/liquors/[id]/page.tsx, src/app/meetings/page.tsx, src/components/LayoutComponents/NavigationComponent.tsx, src/components/ServiceIntroductionComponent/ServiceIntroductionComponent.tsx
**Jira 티켓: [BYOB-202]**
<br>
- 모임 페이지 경로 비활성화 & 네비게이션 바에서 제거
- 홈페이지 소개글 수정
[BYOB-202]: https://swm-alcoholic.atlassian.net/browse/BYOB-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-202] 모임 페이지 비활성화 및 홈페이지 소개글 수정

src/app/meetings/page.tsx, src/components/LayoutComponents/NavigationComponent.tsx
**Jira 티켓: [BYOB-204]**
<br>
모임 기능 부활
[BYOB-204]: https://swm-alcoholic.atlassian.net/browse/BYOB-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-204] 모임 기능 부활

src/app/liquors/[id]/page.tsx, src/app/liquors/page.tsx, src/app/page.tsx, src/components/LayoutComponents/NavigationComponent.tsx, src/components/PriceInfo/PriceInfo.tsx, src/components/ServiceIntroductionComponent/ServiceIntroductionComponentV2.tsx
=> release 2.4.0 가격 비교 기능 추가

src/app/api/price-search/route.ts, src/app/liquors/[id]/page.tsx, src/app/liquors/page.tsx, src/components/PriceInfo/PriceInfo.tsx, src/components/ServiceIntroductionComponent/ServiceIntroductionComponentV2.tsx
**[BYOB-229]**
- 겟주, 이마트, 롯데마트, 빅카메라 추가
<br>
[BYOB-229]: https://swm-alcoholic.atlassian.net/browse/BYOB-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BYOB-229] 가격 비교 다양한 사이트 추가
